version: '3'
services:
  data:
    image: library/postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: todos
  back:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_IP: data
  front:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
