spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    plattform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:${POSTGRES_IP}://data:${POSTGRES_PORT}/todos
    username: docker
    password: docker
